[2022-07-12 14:39:54,858] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T14:34:40.666029+00:00 [queued]>
[2022-07-12 14:39:54,871] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T14:34:40.666029+00:00 [queued]>
[2022-07-12 14:39:54,871] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 14:39:54,871] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-12 14:39:54,872] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 14:39:54,889] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): ingest_data> on 2022-07-12 14:34:40.666029+00:00
[2022-07-12 14:39:54,894] {standard_task_runner.py:52} INFO - Started process 729 to run task
[2022-07-12 14:39:54,897] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'ingest_data', 'manual__2022-07-12T14:34:40.666029+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmp1ntqr87k', '--error-file', '/tmp/tmp02ho1bfs']
[2022-07-12 14:39:54,898] {standard_task_runner.py:80} INFO - Job 4: Subtask ingest_data
[2022-07-12 14:39:54,968] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T14:34:40.666029+00:00 [running]> on host 5a2a9758661b
[2022-07-12 14:39:55,022] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 14:39:55,072] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=ingest_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T14:34:40.666029+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T14:34:40.666029+00:00
[2022-07-12 14:39:55,822] {logging_mixin.py:115} INFO - yellow_taxi_2022_04.parquet /opt/airflow/output_2022-04.parquet
[2022-07-12 14:39:55,822] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data.py", line 20, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-07-12 14:39:55,833] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=data_ingestion_local, task_id=ingest_data, execution_date=20220712T143440, start_date=20220712T143954, end_date=20220712T143955
[2022-07-12 14:39:55,848] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task ingest_data (invalid literal for int() with base 10: 'None'; 729)
[2022-07-12 14:39:55,951] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 14:39:55,990] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
