[2022-07-12 19:07:39,060] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T19:07:24.595810+00:00 [queued]>
[2022-07-12 19:07:39,077] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T19:07:24.595810+00:00 [queued]>
[2022-07-12 19:07:39,078] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 19:07:39,079] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-12 19:07:39,079] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 19:07:39,143] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): convert_to_csv> on 2022-07-12 19:07:24.595810+00:00
[2022-07-12 19:07:39,155] {standard_task_runner.py:52} INFO - Started process 2108 to run task
[2022-07-12 19:07:39,158] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'convert_to_csv', 'manual__2022-07-12T19:07:24.595810+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmpk21m02gv', '--error-file', '/tmp/tmp9nhudml9']
[2022-07-12 19:07:39,160] {standard_task_runner.py:80} INFO - Job 7: Subtask convert_to_csv
[2022-07-12 19:07:39,272] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.convert_to_csv manual__2022-07-12T19:07:24.595810+00:00 [running]> on host 139e0ae5bdf5
[2022-07-12 19:07:39,359] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 19:07:39,440] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=convert_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T19:07:24.595810+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T19:07:24.595810+00:00
[2022-07-12 19:07:58,936] {logging_mixin.py:115} INFO - creating new csv file /opt/airflow/output_2022-04.csv
[2022-07-12 19:07:59,754] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 33, in convert_to_csv_callable
    df.write.option("header","true").csv(new_csv_file_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 1240, in csv
    self._jwrite.csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: path file:/opt/airflow/output_2022-04.csv already exists.
[2022-07-12 19:07:59,792] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_local, task_id=convert_to_csv, execution_date=20220712T190724, start_date=20220712T190739, end_date=20220712T190759
[2022-07-12 19:07:59,811] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task convert_to_csv (path file:/opt/airflow/output_2022-04.csv already exists.; 2108)
[2022-07-12 19:07:59,863] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 19:07:59,923] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
