[2022-07-27 08:47:50,849] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:47:50,850] {processor.py:641} INFO - Processing file /opt/airflow/dags/data_ingestion_local_dag.py for tasks to queue
[2022-07-27 08:47:50,851] {logging_mixin.py:115} INFO - [2022-07-27 08:47:50,851] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:47:52,233] {logging_mixin.py:115} INFO - [2022-07-27 08:47:52,231] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 8, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-27 08:47:52,233] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:47:52,259] {processor.py:161} INFO - Processing /opt/airflow/dags/data_ingestion_local_dag.py took 1.413 seconds
[2022-07-27 08:48:22,354] {processor.py:153} INFO - Started process (PID=199) to work on /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:48:22,355] {processor.py:641} INFO - Processing file /opt/airflow/dags/data_ingestion_local_dag.py for tasks to queue
[2022-07-27 08:48:22,357] {logging_mixin.py:115} INFO - [2022-07-27 08:48:22,356] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:48:22,913] {logging_mixin.py:115} INFO - [2022-07-27 08:48:22,912] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 8, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-27 08:48:22,913] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:48:22,932] {processor.py:161} INFO - Processing /opt/airflow/dags/data_ingestion_local_dag.py took 0.581 seconds
[2022-07-27 08:48:53,016] {processor.py:153} INFO - Started process (PID=231) to work on /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:48:53,016] {processor.py:641} INFO - Processing file /opt/airflow/dags/data_ingestion_local_dag.py for tasks to queue
[2022-07-27 08:48:53,017] {logging_mixin.py:115} INFO - [2022-07-27 08:48:53,017] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:48:53,522] {logging_mixin.py:115} INFO - [2022-07-27 08:48:53,521] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 8, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-27 08:48:53,522] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:48:53,545] {processor.py:161} INFO - Processing /opt/airflow/dags/data_ingestion_local_dag.py took 0.533 seconds
[2022-07-27 08:49:23,630] {processor.py:153} INFO - Started process (PID=255) to work on /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:49:23,631] {processor.py:641} INFO - Processing file /opt/airflow/dags/data_ingestion_local_dag.py for tasks to queue
[2022-07-27 08:49:23,632] {logging_mixin.py:115} INFO - [2022-07-27 08:49:23,632] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:49:24,195] {logging_mixin.py:115} INFO - [2022-07-27 08:49:24,194] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/data_ingestion_local_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion_local_dag.py", line 8, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2022-07-27 08:49:24,196] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion_local_dag.py
[2022-07-27 08:49:24,215] {processor.py:161} INFO - Processing /opt/airflow/dags/data_ingestion_local_dag.py took 0.589 seconds
