[2022-07-12 20:50:46,982] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:44:16.802599+00:00 [queued]>
[2022-07-12 20:50:46,995] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:44:16.802599+00:00 [queued]>
[2022-07-12 20:50:46,995] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:50:46,996] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-12 20:50:46,996] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 20:50:47,014] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): ingest_data> on 2022-07-12 20:44:16.802599+00:00
[2022-07-12 20:50:47,021] {standard_task_runner.py:52} INFO - Started process 2999 to run task
[2022-07-12 20:50:47,024] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_ingestion_local', 'ingest_data', 'manual__2022-07-12T20:44:16.802599+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local_dag.py', '--cfg-path', '/tmp/tmp_bi650po', '--error-file', '/tmp/tmpi_z01vxh']
[2022-07-12 20:50:47,026] {standard_task_runner.py:80} INFO - Job 36: Subtask ingest_data
[2022-07-12 20:50:47,107] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_local.ingest_data manual__2022-07-12T20:44:16.802599+00:00 [running]> on host 139e0ae5bdf5
[2022-07-12 20:50:47,170] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-07-12 20:50:47,228] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_ingestion_local
AIRFLOW_CTX_TASK_ID=ingest_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T20:44:16.802599+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T20:44:16.802599+00:00
[2022-07-12 20:50:47,229] {logging_mixin.py:115} INFO - *** *** pgdatabase 5432 ny_taxi yellow_taxi_2022_04 /opt/airflow/output_2022-04.parquet
[2022-07-12 20:50:47,230] {logging_mixin.py:115} INFO - user is ***
[2022-07-12 20:51:38,655] {logging_mixin.py:115} INFO - creating new csv file /opt/airflow/output_2022-04.csv
[2022-07-12 20:51:39,050] {logging_mixin.py:115} INFO - Creating new connection
[2022-07-12 20:51:39,057] {logging_mixin.py:115} INFO - Connection successfully
[2022-07-12 20:51:57,386] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data.py", line 37, in ingest_callable
    if df == None:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1538, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[2022-07-12 20:51:57,399] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=data_ingestion_local, task_id=ingest_data, execution_date=20220712T204416, start_date=20220712T205046, end_date=20220712T205157
[2022-07-12 20:51:57,418] {standard_task_runner.py:97} ERROR - Failed to execute job 36 for task ingest_data (The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().; 2999)
[2022-07-12 20:51:57,563] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 20:51:57,595] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
